apiVersion: v1
kind: Secret
metadata:
  name: mysql-Secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: VGVzdDEyMw==
  MYSQL_DATABASE: YmFua2FwcGRi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: "bankappdb"

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fstype: ext4
reclaimPolicy: Retain
volumeBindingMode: waitForFirstConsumer

---

apiVersion: v1 
kind: PersistenceVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  StorageClassName: ebs-sc
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec: 
  selector: #def information to be deployed 
    matchLabels:  
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8           
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
          configMapKeyRef:
            name: mysql-config
            key: MYSQL_DATABASE
        ports:
        - containerPort: 3306
        volumeMounts:
        - mounthPath: /var/lib/mysql
          name: mysql-data
        resources:
          requests: #mininum request
            memory: "512Mi"
            cpu: "500m"
          limits: #maxium request   
            memory: "1Gi"
            cpu: "1"
      volumes:
      - name: mysql-data
        persistenceVolumeClaim:
          claimName: mysql-pvc    

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-Service
spec:
  ports:  
