#Resource for Secrets
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: VGVzdDEyMw==
  MYSQL_DATABASE: YmFua2FwcGRi

---
#Resource for Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: "bankappdb"

---
#Resource for Storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fstype: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---
#Resource for Persistent Volume Claim
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 5Gi

---
#Resource for MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:  
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8           
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret  # Fixed: lowercase
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:  # Fixed: proper indentation
              name: mysql-config
              key: MYSQL_DATABASE
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql  # Fixed: mountPath not mounthPath
          name: mysql-data
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc    

---
#Resource for mysql Service
apiVersion: v1
kind: Service  # Fixed: Capital S in Service
metadata:
  name: mysql-service  # Fixed: lowercase
spec:
  ports:  
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql  

---
#Resource for bankapp Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: bankapp
  template:  
    metadata:
      labels:
        app: bankapp  # Fixed: proper key-value format
    spec:  
      containers: 
      - name: bankapp
        image: castromeka/bankapp
        ports:  # Fixed: indentation
        - containerPort: 8080
        env:  # Fixed: indentation
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/bankappdb?useSSL=false&serverTimezone=UTC
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

---
# Resource for Bankapp service
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
spec:
  type: LoadBalancer  
  ports:   
  - port: 80
    targetPort: 8080    
  selector: 
    app: bankapp